from sqlalchemy.orm import Session
from sqlalchemy import func
import csv
import io
from datetime import datetime
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from ..models import Issue, IssueStatus, Urgency, Alert

def generate_csv_export(db: Session, filters: dict = None) -> io.StringIO:
    """
    Generates a raw CSV dump of Issues based on filters.
    """
    query = db.query(Issue)
    
    # Apply basic filters if provided
    if filters:
        if filters.get('status'):
            query = query.filter(Issue.status == filters['status'])
        if filters.get('urgency'):
            query = query.filter(Issue.urgency == filters['urgency'])
        if filters.get('region_id'):
            query = query.filter(Issue.region_id == filters['region_id'])

    issues = query.all()
    
    output = io.StringIO()
    writer = csv.writer(output)
    
    # Header
    writer.writerow(['ID', 'Title', 'Description', 'Category', 'Urgency', 'Status', 'Location', 'Reporter ID', 'Created At'])
    
    # Rows
    for issue in issues:
        writer.writerow([
            issue.id,
            issue.title,
            issue.description,
            issue.category,
            issue.urgency.value,
            issue.status.value,
            issue.location,
            issue.reporter_id,
            issue.created_at.isoformat() if issue.created_at else ''
        ])
    
    output.seek(0)
    return output

def generate_pdf_summary(db: Session, user_name: str) -> io.BytesIO:
    """
    Generates a PDF Executive Summary using ReportLab.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    elements = []

    # Title
    title_style = ParagraphStyle(
        'Title',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#0c4a6e'), # TN-900
        spaceAfter=20
    )
    elements.append(Paragraph("Civic Radar TN - Executive Summary", title_style))
    elements.append(Paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles['Normal']))
    elements.append(Paragraph(f"Generated by: {user_name}", styles['Normal']))
    elements.append(Spacer(1, 20))

    # --- Section 1: Key Metrics ---
    elements.append(Paragraph("Key Metrics", styles['Heading2']))
    
    total_issues = db.query(Issue).count()
    open_issues = db.query(Issue).filter(Issue.status == IssueStatus.OPEN).count()
    resolved_issues = db.query(Issue).filter(Issue.status == IssueStatus.RESOLVED).count()
    critical_alerts = db.query(Alert).count() # Simplified

    metrics_data = [
        ['Metric', 'Count'],
        ['Total Reports', str(total_issues)],
        ['Open Pending', str(open_issues)],
        ['Successfully Resolved', str(resolved_issues)],
        ['System Alerts Triggered', str(critical_alerts)]
    ]

    t = Table(metrics_data, colWidths=[200, 100])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (1, 0), colors.HexColor('#0ea5e9')),
        ('TEXTCOLOR', (0, 0), (1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
        ('GRID', (0, 0), (-1, -1), 1, colors.black)
    ]))
    elements.append(t)
    elements.append(Spacer(1, 20))

    # --- Section 2: Critical Issues Snapshot ---
    elements.append(Paragraph("Critical Urgency Reports (Top 10)", styles['Heading2']))
    
    criticals = db.query(Issue).filter(Issue.urgency == Urgency.CRITICAL).order_by(Issue.created_at.desc()).limit(10).all()
    
    if criticals:
        crit_data = [['Title', 'Location', 'Status']]
        for c in criticals:
            crit_data.append([c.title[:40], c.location[:30], c.status.value])
        
        t2 = Table(crit_data, colWidths=[250, 150, 100])
        t2.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#ef4444')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.grey),
        ]))
        elements.append(t2)
    else:
        elements.append(Paragraph("No critical issues found.", styles['Normal']))

    elements.append(Spacer(1, 20))
    
    # Footer / Disclaimer
    elements.append(Spacer(1, 40))
    elements.append(Paragraph("Confidential - Government of Tamil Nadu", styles['Italic']))

    doc.build(elements)
    buffer.seek(0)
    return buffer